### ISSUE TITLE
Create login/signup endpoints.

### ISSUE THREAD

**Issue by Dogacel** [Dogacel/Kalas-Iris#11]
- [ ] Store the user in the mongodb.
- [ ] Required fields: name, password, email.
- [ ] Don't allow duplicates.

**Comment by AtaAtasoy** [comment]
Implemented the listed features on the "login-signup-endpoint" branch. Did not create a Pull Request, since I plan on enhancing the login feature to support logins with email or username in the same input field and I also plan on implementing an authorization token to assign to a logged in user, which allows to access the website without authentication for a period of time. Also, account confirmation via email should be implemented.

**Comment by Dogacel** [comment]
I think you can always open a pull request and label it as "do not merge" or "wip". Or you can draft it. So that you don't have to worry about reporting your progress in issue, we can just see your commits.

**Comment by Dogacel** [comment]
@Dogacel So I will be sure that you are not lying.

**Comment by AtaAtasoy** [comment]
This issue is complete, thus i'm closing it
