### ISSUE TITLE
Create a welcome page for demonstration.

### ISSUE THREAD

**Issue by Dogacel** [Dogacel/Kalas-Iris#14]
Atleast we should not greet the user with a blank page.

**Comment by AtaAtasoy** [comment]
I think we can add a big slideshow (Carousel) of screenshots as the major component of this page. We should finalize the image annotation page so that we can add its screenshot to the slides. 
We can also maybe add GIFs or a create an informative video (similar to ones made in CS319 as it should showcase the features of the program.)
